Removing the verify stage until server and client examples can be combined

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,12 +25,12 @@ jobs:
       - name: Test
         run: ctest --output-on-failure
 
-      - name: Verify
-        run: |
-          $locationOfSamples = gci -Path . -Filter ciTokenizerExample.exe -Recurse -ErrorAction SilentlyContinue -Force
-          cd $locationOfSamples.DirectoryName
-          $files = gci *.exe
-          foreach ($file in $files) { echo "Hello World!*" | cmd /c $file; if (-not $?) { echo "" } }
+      # - name: Verify
+      #   run: |
+      #     $locationOfSamples = gci -Path . -Filter ciTokenizerExample.exe -Recurse -ErrorAction SilentlyContinue -Force
+      #     cd $locationOfSamples.DirectoryName
+      #     $files = gci *.exe
+      #     foreach ($file in $files) { echo "Hello World!*" | cmd /c $file; if (-not $?) { echo "" } }
 
   nix-builds:
     runs-on: ${{ matrix.os }}
